"""empty message

Revision ID: 44d6ed9ca0d4
Revises: a496372a0c8c
Create Date: 2026-09-27 23:38:14.459680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d6ed9ca0d4'
down_revision: Union[str, Sequence[str], None] = 'a496372a0c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('role', sa.String(length=250), nullable=False, server_default='user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
